添加网关接口（查看任务状态、查看结果、对平台和算子的元信息的修改）
DASLab-CLIC/CLIC pull request #3
Opened 2021-10-26 08:54 UTC by uestcljx

所有网关api均已通过postman测试，功能正确。

查看任务状态：返回job的状态信息，包括执行时间，执行状态，subplan, nodeinfo等等

查看结果：返回各stage的sink中的写入文件路径

对平台和算子的元信息修改：修改平台和算子的配置信息

2021-11-01 06:12 UTC, uestcljx commented
接口文档：https://www.showdoc.com.cn/1678421066255855/7896648227559991

2021-11-04 07:07 UTC, NKcqx commented on executable-operator/executable-spark/src/main/java/fdu/daslab/executable/spark/utils/SparkInitUtil.java
> +            sparkContext = new JavaSparkContext(new SparkConf().setMaster("local[*]").setAppName("default"));
不能在代码里指定 `master`

2021-11-04 07:28 UTC, NKcqx commented on gateway-center/src/main/java/fdu/daslab/gatewaycenter/controller/JobController.java
> +    public R checkJob(@RequestParam String jobName){
用 `jobName` 提交任务，返回 `jobID`，之后用  `jobID` 查看/控制 任务

2021-11-04 07:41 UTC, NKcqx approved these changes
写在评论里了，先通过了，里面的问题后续将提为 issue 另寻他人处理

2021-11-05 05:57 UTC, zjchenn requested changes
总体看上去很好，测试也很完整。
comments里面的那一处地方需要改回去，另外能不能麻烦你把接口文档的文件放在doc区里面？后续我们会整理一下

2021-11-05 05:57 UTC, zjchenn commented on executor-center/src/main/java/fdu/daslab/executorcenter/adapter/ParamAdapter.java
> +    @Value("${dag.localPrefix}")
这个参数是因为本地测试才修改的吗？请改回prefix，要和deploy/executor-centor-config.yaml中的参数对应，否则无法在Kubernetes环境中解析到正确参数

2021-11-05 05:57 UTC, zjchenn commented on executor-center/src/main/resources/application.yaml
> +  localPrefix: D:\study\data\Result # 本地测试用
application中.yaml修改没有问题，即使放在k8s环境中也不会读取这部分内容

2021-11-05 08:33 UTC, uestcljx commented on executor-center/src/main/java/fdu/daslab/executorcenter/adapter/ParamAdapter.java
> +    @Value("${dag.localPrefix}")
好滴，本地测试用的配置参数已在commit ab463da 和commit 9bfa7cc 中删除。

gateway api文档已经写在/docs路径下了（见commit d8967c4 )

2021-11-05 08:40 UTC, uestcljx commented on executable-operator/executable-spark/src/main/java/fdu/daslab/executable/spark/utils/SparkInitUtil.java
> +            sparkContext = new JavaSparkContext(new SparkConf().setMaster("local[*]").setAppName("default"));
好滴，已在 c4c3f1d 中修改

2021-11-05 09:13 UTC, zjchenn commented on executor-center/src/main/java/fdu/daslab/executorcenter/adapter/ParamAdapter.java
> +    @Value("${dag.localPrefix}")
ok，辛苦了 : )

2021-11-05 09:13 UTC, zjchenn approved these changes

2021-11-05 09:13 UTC, merged